/* Generated by Yosys 0.39 (git sha1 00338082b, g++ 13.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -Os) */

(* top =  1  *)
(* src = "./mul8s_1KV8.v:19.1-100.10" *)
module mul8s_1KV8(A, B, O);
  (* src = "./mul8s_1KV8.v:34.33-34.44" *)
  wire _0000_;
  (* src = "./mul8s_1KV8.v:35.34-35.45" *)
  wire _0001_;
  (* src = "./mul8s_1KV8.v:36.34-36.45" *)
  wire _0002_;
  (* src = "./mul8s_1KV8.v:37.34-37.45" *)
  wire _0003_;
  (* src = "./mul8s_1KV8.v:38.34-38.45" *)
  wire _0004_;
  (* src = "./mul8s_1KV8.v:39.34-39.45" *)
  wire _0005_;
  (* src = "./mul8s_1KV8.v:40.34-40.45" *)
  wire _0006_;
  (* src = "./mul8s_1KV8.v:42.45-42.56" *)
  wire _0007_;
  (* src = "./mul8s_1KV8.v:43.45-43.56" *)
  wire _0008_;
  (* src = "./mul8s_1KV8.v:44.45-44.56" *)
  wire _0009_;
  (* src = "./mul8s_1KV8.v:45.45-45.56" *)
  wire _0010_;
  (* src = "./mul8s_1KV8.v:46.45-46.56" *)
  wire _0011_;
  (* src = "./mul8s_1KV8.v:47.45-47.56" *)
  wire _0012_;
  (* src = "./mul8s_1KV8.v:48.45-48.56" *)
  wire _0013_;
  (* src = "./mul8s_1KV8.v:50.45-50.56" *)
  wire _0014_;
  (* src = "./mul8s_1KV8.v:51.45-51.56" *)
  wire _0015_;
  (* src = "./mul8s_1KV8.v:52.45-52.56" *)
  wire _0016_;
  (* src = "./mul8s_1KV8.v:53.45-53.56" *)
  wire _0017_;
  (* src = "./mul8s_1KV8.v:54.45-54.56" *)
  wire _0018_;
  (* src = "./mul8s_1KV8.v:55.45-55.56" *)
  wire _0019_;
  (* src = "./mul8s_1KV8.v:56.45-56.56" *)
  wire _0020_;
  (* src = "./mul8s_1KV8.v:58.45-58.56" *)
  wire _0021_;
  (* src = "./mul8s_1KV8.v:59.45-59.56" *)
  wire _0022_;
  (* src = "./mul8s_1KV8.v:60.45-60.56" *)
  wire _0023_;
  (* src = "./mul8s_1KV8.v:61.45-61.56" *)
  wire _0024_;
  (* src = "./mul8s_1KV8.v:62.45-62.56" *)
  wire _0025_;
  (* src = "./mul8s_1KV8.v:63.45-63.56" *)
  wire _0026_;
  (* src = "./mul8s_1KV8.v:64.45-64.56" *)
  wire _0027_;
  (* src = "./mul8s_1KV8.v:66.45-66.56" *)
  wire _0028_;
  (* src = "./mul8s_1KV8.v:67.45-67.56" *)
  wire _0029_;
  (* src = "./mul8s_1KV8.v:68.45-68.56" *)
  wire _0030_;
  (* src = "./mul8s_1KV8.v:69.45-69.56" *)
  wire _0031_;
  (* src = "./mul8s_1KV8.v:70.45-70.56" *)
  wire _0032_;
  (* src = "./mul8s_1KV8.v:71.45-71.56" *)
  wire _0033_;
  (* src = "./mul8s_1KV8.v:72.45-72.56" *)
  wire _0034_;
  (* src = "./mul8s_1KV8.v:74.45-74.56" *)
  wire _0035_;
  (* src = "./mul8s_1KV8.v:75.45-75.56" *)
  wire _0036_;
  (* src = "./mul8s_1KV8.v:76.45-76.56" *)
  wire _0037_;
  (* src = "./mul8s_1KV8.v:77.45-77.56" *)
  wire _0038_;
  (* src = "./mul8s_1KV8.v:78.45-78.56" *)
  wire _0039_;
  (* src = "./mul8s_1KV8.v:79.45-79.56" *)
  wire _0040_;
  (* src = "./mul8s_1KV8.v:80.45-80.56" *)
  wire _0041_;
  (* src = "./mul8s_1KV8.v:89.34-89.45" *)
  wire _0042_;
  (* src = "./mul8s_1KV8.v:41.32-41.46" *)
  wire _0043_;
  (* src = "./mul8s_1KV8.v:49.33-49.47" *)
  wire _0044_;
  (* src = "./mul8s_1KV8.v:57.33-57.47" *)
  wire _0045_;
  (* src = "./mul8s_1KV8.v:65.33-65.47" *)
  wire _0046_;
  (* src = "./mul8s_1KV8.v:73.33-73.47" *)
  wire _0047_;
  (* src = "./mul8s_1KV8.v:81.33-81.47" *)
  wire _0048_;
  (* src = "./mul8s_1KV8.v:82.44-82.58" *)
  wire _0049_;
  (* src = "./mul8s_1KV8.v:83.44-83.58" *)
  wire _0050_;
  (* src = "./mul8s_1KV8.v:84.44-84.58" *)
  wire _0051_;
  (* src = "./mul8s_1KV8.v:85.44-85.58" *)
  wire _0052_;
  (* src = "./mul8s_1KV8.v:86.44-86.58" *)
  wire _0053_;
  (* src = "./mul8s_1KV8.v:87.44-87.58" *)
  wire _0054_;
  (* src = "./mul8s_1KV8.v:88.44-88.58" *)
  wire _0055_;
  (* src = "./mul8s_1KV8.v:20.15-20.16" *)
  wire _0056_;
  (* src = "./mul8s_1KV8.v:20.15-20.16" *)
  wire _0057_;
  (* src = "./mul8s_1KV8.v:20.15-20.16" *)
  wire _0058_;
  (* src = "./mul8s_1KV8.v:20.15-20.16" *)
  wire _0059_;
  (* src = "./mul8s_1KV8.v:20.15-20.16" *)
  wire _0060_;
  (* src = "./mul8s_1KV8.v:20.15-20.16" *)
  wire _0061_;
  (* src = "./mul8s_1KV8.v:20.15-20.16" *)
  wire _0062_;
  (* src = "./mul8s_1KV8.v:20.15-20.16" *)
  wire _0063_;
  (* src = "./mul8s_1KV8.v:21.15-21.16" *)
  wire _0064_;
  (* src = "./mul8s_1KV8.v:21.15-21.16" *)
  wire _0065_;
  (* src = "./mul8s_1KV8.v:21.15-21.16" *)
  wire _0066_;
  (* src = "./mul8s_1KV8.v:21.15-21.16" *)
  wire _0067_;
  (* src = "./mul8s_1KV8.v:21.15-21.16" *)
  wire _0068_;
  (* src = "./mul8s_1KV8.v:21.15-21.16" *)
  wire _0069_;
  (* src = "./mul8s_1KV8.v:21.15-21.16" *)
  wire _0070_;
  (* src = "./mul8s_1KV8.v:21.15-21.16" *)
  wire _0071_;
  (* src = "./mul8s_1KV8.v:24.392-24.397" *)
  wire _0072_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0073_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0074_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0075_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0076_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0077_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0078_;
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire _0079_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0080_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0081_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0082_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0083_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0084_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0085_;
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire _0086_;
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  (* src = "./mul8s_1KV8.v:20.15-20.16" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "./mul8s_1KV8.v:21.15-21.16" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "./mul8s_1KV8.v:24.8-24.13" *)
  wire C_1_0;
  (* src = "./mul8s_1KV8.v:24.14-24.19" *)
  wire C_1_1;
  (* src = "./mul8s_1KV8.v:24.20-24.25" *)
  wire C_1_2;
  (* src = "./mul8s_1KV8.v:24.26-24.31" *)
  wire C_1_3;
  (* src = "./mul8s_1KV8.v:24.32-24.37" *)
  wire C_1_4;
  (* src = "./mul8s_1KV8.v:24.38-24.43" *)
  wire C_1_5;
  (* src = "./mul8s_1KV8.v:24.44-24.49" *)
  wire C_1_6;
  (* src = "./mul8s_1KV8.v:24.50-24.55" *)
  wire C_1_7;
  (* src = "./mul8s_1KV8.v:24.56-24.61" *)
  wire C_2_0;
  (* src = "./mul8s_1KV8.v:24.62-24.67" *)
  wire C_2_1;
  (* src = "./mul8s_1KV8.v:24.68-24.73" *)
  wire C_2_2;
  (* src = "./mul8s_1KV8.v:24.74-24.79" *)
  wire C_2_3;
  (* src = "./mul8s_1KV8.v:24.80-24.85" *)
  wire C_2_4;
  (* src = "./mul8s_1KV8.v:24.86-24.91" *)
  wire C_2_5;
  (* src = "./mul8s_1KV8.v:24.92-24.97" *)
  wire C_2_6;
  (* src = "./mul8s_1KV8.v:24.98-24.103" *)
  wire C_2_7;
  (* src = "./mul8s_1KV8.v:24.104-24.109" *)
  wire C_3_0;
  (* src = "./mul8s_1KV8.v:24.110-24.115" *)
  wire C_3_1;
  (* src = "./mul8s_1KV8.v:24.116-24.121" *)
  wire C_3_2;
  (* src = "./mul8s_1KV8.v:24.122-24.127" *)
  wire C_3_3;
  (* src = "./mul8s_1KV8.v:24.128-24.133" *)
  wire C_3_4;
  (* src = "./mul8s_1KV8.v:24.134-24.139" *)
  wire C_3_5;
  (* src = "./mul8s_1KV8.v:24.140-24.145" *)
  wire C_3_6;
  (* src = "./mul8s_1KV8.v:24.146-24.151" *)
  wire C_3_7;
  (* src = "./mul8s_1KV8.v:24.152-24.157" *)
  wire C_4_0;
  (* src = "./mul8s_1KV8.v:24.158-24.163" *)
  wire C_4_1;
  (* src = "./mul8s_1KV8.v:24.164-24.169" *)
  wire C_4_2;
  (* src = "./mul8s_1KV8.v:24.170-24.175" *)
  wire C_4_3;
  (* src = "./mul8s_1KV8.v:24.176-24.181" *)
  wire C_4_4;
  (* src = "./mul8s_1KV8.v:24.182-24.187" *)
  wire C_4_5;
  (* src = "./mul8s_1KV8.v:24.188-24.193" *)
  wire C_4_6;
  (* src = "./mul8s_1KV8.v:24.194-24.199" *)
  wire C_4_7;
  (* src = "./mul8s_1KV8.v:24.200-24.205" *)
  wire C_5_0;
  (* src = "./mul8s_1KV8.v:24.206-24.211" *)
  wire C_5_1;
  (* src = "./mul8s_1KV8.v:24.212-24.217" *)
  wire C_5_2;
  (* src = "./mul8s_1KV8.v:24.218-24.223" *)
  wire C_5_3;
  (* src = "./mul8s_1KV8.v:24.224-24.229" *)
  wire C_5_4;
  (* src = "./mul8s_1KV8.v:24.230-24.235" *)
  wire C_5_5;
  (* src = "./mul8s_1KV8.v:24.236-24.241" *)
  wire C_5_6;
  (* src = "./mul8s_1KV8.v:24.242-24.247" *)
  wire C_5_7;
  (* src = "./mul8s_1KV8.v:24.248-24.253" *)
  wire C_6_0;
  (* src = "./mul8s_1KV8.v:24.254-24.259" *)
  wire C_6_1;
  (* src = "./mul8s_1KV8.v:24.260-24.265" *)
  wire C_6_2;
  (* src = "./mul8s_1KV8.v:24.266-24.271" *)
  wire C_6_3;
  (* src = "./mul8s_1KV8.v:24.272-24.277" *)
  wire C_6_4;
  (* src = "./mul8s_1KV8.v:24.278-24.283" *)
  wire C_6_5;
  (* src = "./mul8s_1KV8.v:24.284-24.289" *)
  wire C_6_6;
  (* src = "./mul8s_1KV8.v:24.290-24.295" *)
  wire C_6_7;
  (* src = "./mul8s_1KV8.v:24.296-24.301" *)
  wire C_7_0;
  (* src = "./mul8s_1KV8.v:24.302-24.307" *)
  wire C_7_1;
  (* src = "./mul8s_1KV8.v:24.308-24.313" *)
  wire C_7_2;
  (* src = "./mul8s_1KV8.v:24.314-24.319" *)
  wire C_7_3;
  (* src = "./mul8s_1KV8.v:24.320-24.325" *)
  wire C_7_4;
  (* src = "./mul8s_1KV8.v:24.326-24.331" *)
  wire C_7_5;
  (* src = "./mul8s_1KV8.v:24.332-24.337" *)
  wire C_7_6;
  (* src = "./mul8s_1KV8.v:24.338-24.343" *)
  wire C_7_7;
  (* src = "./mul8s_1KV8.v:24.344-24.349" *)
  wire C_8_0;
  (* src = "./mul8s_1KV8.v:24.350-24.355" *)
  wire C_8_1;
  (* src = "./mul8s_1KV8.v:24.356-24.361" *)
  wire C_8_2;
  (* src = "./mul8s_1KV8.v:24.362-24.367" *)
  wire C_8_3;
  (* src = "./mul8s_1KV8.v:24.368-24.373" *)
  wire C_8_4;
  (* src = "./mul8s_1KV8.v:24.374-24.379" *)
  wire C_8_5;
  (* src = "./mul8s_1KV8.v:24.380-24.385" *)
  wire C_8_6;
  (* src = "./mul8s_1KV8.v:24.386-24.391" *)
  (* unused_bits = "0" *)
  wire C_8_7;
  (* src = "./mul8s_1KV8.v:22.17-22.18" *)
  output [15:0] O;
  wire [15:0] O;
  (* src = "./mul8s_1KV8.v:24.392-24.397" *)
  wire S_0_0;
  (* src = "./mul8s_1KV8.v:24.398-24.403" *)
  wire S_0_1;
  (* src = "./mul8s_1KV8.v:24.404-24.409" *)
  wire S_0_2;
  (* src = "./mul8s_1KV8.v:24.410-24.415" *)
  wire S_0_3;
  (* src = "./mul8s_1KV8.v:24.416-24.421" *)
  wire S_0_4;
  (* src = "./mul8s_1KV8.v:24.422-24.427" *)
  wire S_0_5;
  (* src = "./mul8s_1KV8.v:24.428-24.433" *)
  wire S_0_6;
  (* src = "./mul8s_1KV8.v:24.434-24.439" *)
  wire S_0_7;
  (* src = "./mul8s_1KV8.v:24.440-24.445" *)
  wire S_1_0;
  (* src = "./mul8s_1KV8.v:24.446-24.451" *)
  wire S_1_1;
  (* src = "./mul8s_1KV8.v:24.452-24.457" *)
  wire S_1_2;
  (* src = "./mul8s_1KV8.v:24.458-24.463" *)
  wire S_1_3;
  (* src = "./mul8s_1KV8.v:24.464-24.469" *)
  wire S_1_4;
  (* src = "./mul8s_1KV8.v:24.470-24.475" *)
  wire S_1_5;
  (* src = "./mul8s_1KV8.v:24.476-24.481" *)
  wire S_1_6;
  (* src = "./mul8s_1KV8.v:24.482-24.487" *)
  wire S_1_7;
  (* src = "./mul8s_1KV8.v:24.488-24.493" *)
  wire S_2_0;
  (* src = "./mul8s_1KV8.v:24.494-24.499" *)
  wire S_2_1;
  (* src = "./mul8s_1KV8.v:24.500-24.505" *)
  wire S_2_2;
  (* src = "./mul8s_1KV8.v:24.506-24.511" *)
  wire S_2_3;
  (* src = "./mul8s_1KV8.v:24.512-24.517" *)
  wire S_2_4;
  (* src = "./mul8s_1KV8.v:24.518-24.523" *)
  wire S_2_5;
  (* src = "./mul8s_1KV8.v:24.524-24.529" *)
  wire S_2_6;
  (* src = "./mul8s_1KV8.v:24.530-24.535" *)
  wire S_2_7;
  (* src = "./mul8s_1KV8.v:24.536-24.541" *)
  wire S_3_0;
  (* src = "./mul8s_1KV8.v:24.542-24.547" *)
  wire S_3_1;
  (* src = "./mul8s_1KV8.v:24.548-24.553" *)
  wire S_3_2;
  (* src = "./mul8s_1KV8.v:24.554-24.559" *)
  wire S_3_3;
  (* src = "./mul8s_1KV8.v:24.560-24.565" *)
  wire S_3_4;
  (* src = "./mul8s_1KV8.v:24.566-24.571" *)
  wire S_3_5;
  (* src = "./mul8s_1KV8.v:24.572-24.577" *)
  wire S_3_6;
  (* src = "./mul8s_1KV8.v:24.578-24.583" *)
  wire S_3_7;
  (* src = "./mul8s_1KV8.v:24.584-24.589" *)
  wire S_4_0;
  (* src = "./mul8s_1KV8.v:24.590-24.595" *)
  wire S_4_1;
  (* src = "./mul8s_1KV8.v:24.596-24.601" *)
  wire S_4_2;
  (* src = "./mul8s_1KV8.v:24.602-24.607" *)
  wire S_4_3;
  (* src = "./mul8s_1KV8.v:24.608-24.613" *)
  wire S_4_4;
  (* src = "./mul8s_1KV8.v:24.614-24.619" *)
  wire S_4_5;
  (* src = "./mul8s_1KV8.v:24.620-24.625" *)
  wire S_4_6;
  (* src = "./mul8s_1KV8.v:24.626-24.631" *)
  wire S_4_7;
  (* src = "./mul8s_1KV8.v:24.632-24.637" *)
  wire S_5_0;
  (* src = "./mul8s_1KV8.v:24.638-24.643" *)
  wire S_5_1;
  (* src = "./mul8s_1KV8.v:24.644-24.649" *)
  wire S_5_2;
  (* src = "./mul8s_1KV8.v:24.650-24.655" *)
  wire S_5_3;
  (* src = "./mul8s_1KV8.v:24.656-24.661" *)
  wire S_5_4;
  (* src = "./mul8s_1KV8.v:24.662-24.667" *)
  wire S_5_5;
  (* src = "./mul8s_1KV8.v:24.668-24.673" *)
  wire S_5_6;
  (* src = "./mul8s_1KV8.v:24.674-24.679" *)
  wire S_5_7;
  (* src = "./mul8s_1KV8.v:24.680-24.685" *)
  wire S_6_0;
  (* src = "./mul8s_1KV8.v:24.686-24.691" *)
  wire S_6_1;
  (* src = "./mul8s_1KV8.v:24.692-24.697" *)
  wire S_6_2;
  (* src = "./mul8s_1KV8.v:24.698-24.703" *)
  wire S_6_3;
  (* src = "./mul8s_1KV8.v:24.704-24.709" *)
  wire S_6_4;
  (* src = "./mul8s_1KV8.v:24.710-24.715" *)
  wire S_6_5;
  (* src = "./mul8s_1KV8.v:24.716-24.721" *)
  wire S_6_6;
  (* src = "./mul8s_1KV8.v:24.722-24.727" *)
  wire S_6_7;
  (* src = "./mul8s_1KV8.v:24.728-24.733" *)
  wire S_7_0;
  (* src = "./mul8s_1KV8.v:24.734-24.739" *)
  wire S_7_1;
  (* src = "./mul8s_1KV8.v:24.740-24.745" *)
  wire S_7_2;
  (* src = "./mul8s_1KV8.v:24.746-24.751" *)
  wire S_7_3;
  (* src = "./mul8s_1KV8.v:24.752-24.757" *)
  wire S_7_4;
  (* src = "./mul8s_1KV8.v:24.758-24.763" *)
  wire S_7_5;
  (* src = "./mul8s_1KV8.v:24.764-24.769" *)
  wire S_7_6;
  (* src = "./mul8s_1KV8.v:24.770-24.775" *)
  wire S_7_7;
  (* src = "./mul8s_1KV8.v:24.776-24.781" *)
  wire S_8_0;
  (* src = "./mul8s_1KV8.v:24.782-24.787" *)
  wire S_8_1;
  (* src = "./mul8s_1KV8.v:24.788-24.793" *)
  wire S_8_2;
  (* src = "./mul8s_1KV8.v:24.794-24.799" *)
  wire S_8_3;
  (* src = "./mul8s_1KV8.v:24.800-24.805" *)
  wire S_8_4;
  (* src = "./mul8s_1KV8.v:24.806-24.811" *)
  wire S_8_5;
  (* src = "./mul8s_1KV8.v:24.812-24.817" *)
  wire S_8_6;
  (* src = "./mul8s_1KV8.v:24.818-24.823" *)
  wire S_8_7;
  (* hdlname = "U10 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U10.A ;
  (* hdlname = "U10 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U10.B ;
  (* hdlname = "U10 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U10.YC ;
  (* hdlname = "U10 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U10.YS ;
  (* hdlname = "U11 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U11.A ;
  (* hdlname = "U11 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U11.B ;
  (* hdlname = "U11 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U11.YC ;
  (* hdlname = "U11 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U11.YS ;
  (* hdlname = "U12 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U12.A ;
  (* hdlname = "U12 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U12.B ;
  (* hdlname = "U12 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U12.YC ;
  (* hdlname = "U12 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U12.YS ;
  (* hdlname = "U13 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U13.A ;
  (* hdlname = "U13 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U13.B ;
  (* hdlname = "U13 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U13.YC ;
  (* hdlname = "U13 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U13.YS ;
  (* hdlname = "U14 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U14.A ;
  (* hdlname = "U14 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U14.B ;
  (* hdlname = "U14 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U14.YC ;
  (* hdlname = "U14 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U14.YS ;
  (* hdlname = "U15 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U15.A ;
  (* hdlname = "U15 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U15.B ;
  (* hdlname = "U15 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U15.YC ;
  (* hdlname = "U15 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U15.YS ;
  (* hdlname = "U16 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U16.A ;
  (* hdlname = "U16 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U16.B ;
  (* hdlname = "U16 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U16.YC ;
  (* hdlname = "U16 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U16.YS ;
  (* hdlname = "U17 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U17.A ;
  (* hdlname = "U17 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U17.B ;
  (* hdlname = "U17 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U17.C ;
  (* hdlname = "U17 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U17.YC ;
  (* hdlname = "U17 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U17.YS ;
  (* hdlname = "U18 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U18.A ;
  (* hdlname = "U18 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U18.B ;
  (* hdlname = "U18 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U18.C ;
  (* hdlname = "U18 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U18.YC ;
  (* hdlname = "U18 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U18.YS ;
  (* hdlname = "U19 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U19.A ;
  (* hdlname = "U19 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U19.B ;
  (* hdlname = "U19 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U19.C ;
  (* hdlname = "U19 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U19.YC ;
  (* hdlname = "U19 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U19.YS ;
  (* hdlname = "U20 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U20.A ;
  (* hdlname = "U20 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U20.B ;
  (* hdlname = "U20 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U20.C ;
  (* hdlname = "U20 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U20.YC ;
  (* hdlname = "U20 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U20.YS ;
  (* hdlname = "U21 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U21.A ;
  (* hdlname = "U21 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U21.B ;
  (* hdlname = "U21 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U21.C ;
  (* hdlname = "U21 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U21.YC ;
  (* hdlname = "U21 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U21.YS ;
  (* hdlname = "U22 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U22.A ;
  (* hdlname = "U22 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U22.B ;
  (* hdlname = "U22 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U22.C ;
  (* hdlname = "U22 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U22.YC ;
  (* hdlname = "U22 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U22.YS ;
  (* hdlname = "U23 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U23.A ;
  (* hdlname = "U23 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U23.B ;
  (* hdlname = "U23 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U23.C ;
  (* hdlname = "U23 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U23.YC ;
  (* hdlname = "U23 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U23.YS ;
  (* hdlname = "U24 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U24.A ;
  (* hdlname = "U24 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U24.B ;
  (* hdlname = "U24 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U24.YC ;
  (* hdlname = "U24 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U24.YS ;
  (* hdlname = "U25 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U25.A ;
  (* hdlname = "U25 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U25.B ;
  (* hdlname = "U25 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U25.C ;
  (* hdlname = "U25 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U25.YC ;
  (* hdlname = "U25 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U25.YS ;
  (* hdlname = "U26 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U26.A ;
  (* hdlname = "U26 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U26.B ;
  (* hdlname = "U26 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U26.C ;
  (* hdlname = "U26 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U26.YC ;
  (* hdlname = "U26 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U26.YS ;
  (* hdlname = "U27 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U27.A ;
  (* hdlname = "U27 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U27.B ;
  (* hdlname = "U27 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U27.C ;
  (* hdlname = "U27 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U27.YC ;
  (* hdlname = "U27 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U27.YS ;
  (* hdlname = "U28 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U28.A ;
  (* hdlname = "U28 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U28.B ;
  (* hdlname = "U28 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U28.C ;
  (* hdlname = "U28 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U28.YC ;
  (* hdlname = "U28 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U28.YS ;
  (* hdlname = "U29 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U29.A ;
  (* hdlname = "U29 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U29.B ;
  (* hdlname = "U29 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U29.C ;
  (* hdlname = "U29 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U29.YC ;
  (* hdlname = "U29 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U29.YS ;
  (* hdlname = "U30 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U30.A ;
  (* hdlname = "U30 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U30.B ;
  (* hdlname = "U30 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U30.C ;
  (* hdlname = "U30 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U30.YC ;
  (* hdlname = "U30 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U30.YS ;
  (* hdlname = "U31 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U31.A ;
  (* hdlname = "U31 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U31.B ;
  (* hdlname = "U31 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U31.C ;
  (* hdlname = "U31 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U31.YC ;
  (* hdlname = "U31 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U31.YS ;
  (* hdlname = "U32 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U32.A ;
  (* hdlname = "U32 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U32.B ;
  (* hdlname = "U32 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U32.YC ;
  (* hdlname = "U32 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U32.YS ;
  (* hdlname = "U33 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U33.A ;
  (* hdlname = "U33 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U33.B ;
  (* hdlname = "U33 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U33.C ;
  (* hdlname = "U33 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U33.YC ;
  (* hdlname = "U33 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U33.YS ;
  (* hdlname = "U34 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U34.A ;
  (* hdlname = "U34 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U34.B ;
  (* hdlname = "U34 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U34.C ;
  (* hdlname = "U34 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U34.YC ;
  (* hdlname = "U34 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U34.YS ;
  (* hdlname = "U35 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U35.A ;
  (* hdlname = "U35 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U35.B ;
  (* hdlname = "U35 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U35.C ;
  (* hdlname = "U35 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U35.YC ;
  (* hdlname = "U35 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U35.YS ;
  (* hdlname = "U36 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U36.A ;
  (* hdlname = "U36 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U36.B ;
  (* hdlname = "U36 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U36.C ;
  (* hdlname = "U36 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U36.YC ;
  (* hdlname = "U36 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U36.YS ;
  (* hdlname = "U37 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U37.A ;
  (* hdlname = "U37 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U37.B ;
  (* hdlname = "U37 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U37.C ;
  (* hdlname = "U37 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U37.YC ;
  (* hdlname = "U37 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U37.YS ;
  (* hdlname = "U38 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U38.A ;
  (* hdlname = "U38 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U38.B ;
  (* hdlname = "U38 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U38.C ;
  (* hdlname = "U38 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U38.YC ;
  (* hdlname = "U38 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U38.YS ;
  (* hdlname = "U39 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U39.A ;
  (* hdlname = "U39 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U39.B ;
  (* hdlname = "U39 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U39.C ;
  (* hdlname = "U39 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U39.YC ;
  (* hdlname = "U39 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U39.YS ;
  (* hdlname = "U40 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U40.A ;
  (* hdlname = "U40 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U40.B ;
  (* hdlname = "U40 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U40.YC ;
  (* hdlname = "U40 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U40.YS ;
  (* hdlname = "U41 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U41.A ;
  (* hdlname = "U41 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U41.B ;
  (* hdlname = "U41 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U41.C ;
  (* hdlname = "U41 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U41.YC ;
  (* hdlname = "U41 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U41.YS ;
  (* hdlname = "U42 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U42.A ;
  (* hdlname = "U42 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U42.B ;
  (* hdlname = "U42 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U42.C ;
  (* hdlname = "U42 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U42.YC ;
  (* hdlname = "U42 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U42.YS ;
  (* hdlname = "U43 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U43.A ;
  (* hdlname = "U43 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U43.B ;
  (* hdlname = "U43 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U43.C ;
  (* hdlname = "U43 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U43.YC ;
  (* hdlname = "U43 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U43.YS ;
  (* hdlname = "U44 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U44.A ;
  (* hdlname = "U44 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U44.B ;
  (* hdlname = "U44 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U44.C ;
  (* hdlname = "U44 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U44.YC ;
  (* hdlname = "U44 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U44.YS ;
  (* hdlname = "U45 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U45.A ;
  (* hdlname = "U45 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U45.B ;
  (* hdlname = "U45 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U45.C ;
  (* hdlname = "U45 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U45.YC ;
  (* hdlname = "U45 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U45.YS ;
  (* hdlname = "U46 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U46.A ;
  (* hdlname = "U46 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U46.B ;
  (* hdlname = "U46 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U46.C ;
  (* hdlname = "U46 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U46.YC ;
  (* hdlname = "U46 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U46.YS ;
  (* hdlname = "U47 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U47.A ;
  (* hdlname = "U47 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U47.B ;
  (* hdlname = "U47 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U47.C ;
  (* hdlname = "U47 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U47.YC ;
  (* hdlname = "U47 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U47.YS ;
  (* hdlname = "U48 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U48.A ;
  (* hdlname = "U48 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U48.B ;
  (* hdlname = "U48 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U48.YC ;
  (* hdlname = "U48 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U48.YS ;
  (* hdlname = "U49 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U49.A ;
  (* hdlname = "U49 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U49.B ;
  (* hdlname = "U49 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U49.C ;
  (* hdlname = "U49 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U49.YC ;
  (* hdlname = "U49 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U49.YS ;
  (* hdlname = "U50 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U50.A ;
  (* hdlname = "U50 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U50.B ;
  (* hdlname = "U50 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U50.C ;
  (* hdlname = "U50 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U50.YC ;
  (* hdlname = "U50 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U50.YS ;
  (* hdlname = "U51 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U51.A ;
  (* hdlname = "U51 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U51.B ;
  (* hdlname = "U51 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U51.C ;
  (* hdlname = "U51 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U51.YC ;
  (* hdlname = "U51 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U51.YS ;
  (* hdlname = "U52 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U52.A ;
  (* hdlname = "U52 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U52.B ;
  (* hdlname = "U52 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U52.C ;
  (* hdlname = "U52 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U52.YC ;
  (* hdlname = "U52 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U52.YS ;
  (* hdlname = "U53 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U53.A ;
  (* hdlname = "U53 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U53.B ;
  (* hdlname = "U53 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U53.C ;
  (* hdlname = "U53 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U53.YC ;
  (* hdlname = "U53 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U53.YS ;
  (* hdlname = "U54 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U54.A ;
  (* hdlname = "U54 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U54.B ;
  (* hdlname = "U54 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U54.C ;
  (* hdlname = "U54 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U54.YC ;
  (* hdlname = "U54 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U54.YS ;
  (* hdlname = "U55 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U55.A ;
  (* hdlname = "U55 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U55.B ;
  (* hdlname = "U55 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U55.C ;
  (* hdlname = "U55 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U55.YC ;
  (* hdlname = "U55 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U55.YS ;
  (* hdlname = "U56 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U56.A ;
  (* hdlname = "U56 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U56.B ;
  (* hdlname = "U56 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U56.YC ;
  (* hdlname = "U56 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U56.YS ;
  (* hdlname = "U57 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U57.A ;
  (* hdlname = "U57 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U57.B ;
  (* hdlname = "U57 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U57.C ;
  (* hdlname = "U57 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U57.YC ;
  (* hdlname = "U57 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U57.YS ;
  (* hdlname = "U58 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U58.A ;
  (* hdlname = "U58 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U58.B ;
  (* hdlname = "U58 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U58.C ;
  (* hdlname = "U58 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U58.YC ;
  (* hdlname = "U58 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U58.YS ;
  (* hdlname = "U59 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U59.A ;
  (* hdlname = "U59 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U59.B ;
  (* hdlname = "U59 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U59.C ;
  (* hdlname = "U59 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U59.YC ;
  (* hdlname = "U59 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U59.YS ;
  (* hdlname = "U60 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U60.A ;
  (* hdlname = "U60 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U60.B ;
  (* hdlname = "U60 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U60.C ;
  (* hdlname = "U60 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U60.YC ;
  (* hdlname = "U60 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U60.YS ;
  (* hdlname = "U61 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U61.A ;
  (* hdlname = "U61 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U61.B ;
  (* hdlname = "U61 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U61.C ;
  (* hdlname = "U61 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U61.YC ;
  (* hdlname = "U61 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U61.YS ;
  (* hdlname = "U62 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U62.A ;
  (* hdlname = "U62 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U62.B ;
  (* hdlname = "U62 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U62.C ;
  (* hdlname = "U62 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U62.YC ;
  (* hdlname = "U62 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U62.YS ;
  (* hdlname = "U63 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U63.A ;
  (* hdlname = "U63 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U63.B ;
  (* hdlname = "U63 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U63.C ;
  (* hdlname = "U63 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U63.YC ;
  (* hdlname = "U63 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U63.YS ;
  (* hdlname = "U64 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U64.A ;
  (* hdlname = "U64 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U64.B ;
  (* hdlname = "U64 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U64.YC ;
  (* hdlname = "U64 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U64.YS ;
  (* hdlname = "U65 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U65.A ;
  (* hdlname = "U65 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U65.B ;
  (* hdlname = "U65 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U65.YC ;
  (* hdlname = "U65 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U65.YS ;
  (* hdlname = "U66 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U66.A ;
  (* hdlname = "U66 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U66.B ;
  (* hdlname = "U66 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U66.C ;
  (* hdlname = "U66 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U66.YC ;
  (* hdlname = "U66 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U66.YS ;
  (* hdlname = "U67 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U67.A ;
  (* hdlname = "U67 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U67.B ;
  (* hdlname = "U67 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U67.C ;
  (* hdlname = "U67 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U67.YC ;
  (* hdlname = "U67 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U67.YS ;
  (* hdlname = "U68 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U68.A ;
  (* hdlname = "U68 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U68.B ;
  (* hdlname = "U68 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U68.C ;
  (* hdlname = "U68 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U68.YC ;
  (* hdlname = "U68 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U68.YS ;
  (* hdlname = "U69 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U69.A ;
  (* hdlname = "U69 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U69.B ;
  (* hdlname = "U69 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U69.C ;
  (* hdlname = "U69 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U69.YC ;
  (* hdlname = "U69 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U69.YS ;
  (* hdlname = "U70 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U70.A ;
  (* hdlname = "U70 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U70.B ;
  (* hdlname = "U70 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U70.C ;
  (* hdlname = "U70 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U70.YC ;
  (* hdlname = "U70 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U70.YS ;
  (* hdlname = "U71 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U71.A ;
  (* hdlname = "U71 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U71.B ;
  (* hdlname = "U71 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U71.C ;
  (* hdlname = "U71 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U71.YC ;
  (* hdlname = "U71 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U71.YS ;
  (* hdlname = "U72 A" *)
  (* src = "./mul8s_1KV8.v:108.26-108.27" *)
  wire \U72.A ;
  (* hdlname = "U72 B" *)
  (* src = "./mul8s_1KV8.v:108.35-108.36" *)
  wire \U72.B ;
  (* hdlname = "U72 C" *)
  (* src = "./mul8s_1KV8.v:108.44-108.45" *)
  wire \U72.C ;
  (* hdlname = "U72 YC" *)
  (* src = "./mul8s_1KV8.v:108.65-108.67" *)
  wire \U72.YC ;
  (* hdlname = "U72 YS" *)
  (* src = "./mul8s_1KV8.v:108.54-108.56" *)
  wire \U72.YS ;
  (* hdlname = "U9 A" *)
  (* src = "./mul8s_1KV8.v:103.26-103.27" *)
  wire \U9.A ;
  (* hdlname = "U9 B" *)
  (* src = "./mul8s_1KV8.v:103.35-103.36" *)
  wire \U9.B ;
  (* hdlname = "U9 YC" *)
  (* src = "./mul8s_1KV8.v:103.56-103.58" *)
  wire \U9.YC ;
  (* hdlname = "U9 YS" *)
  (* src = "./mul8s_1KV8.v:103.45-103.47" *)
  wire \U9.YS ;
  assign _0322_ = ~(_0058_ & _0064_);
  assign _0333_ = ~(_0056_ & _0065_);
  assign _0343_ = _0057_ & _0064_;
  assign _0354_ = _0057_ & _0065_;
  assign _0072_ = _0056_ & _0064_;
  assign _0374_ = _0354_ & _0072_;
  assign _0384_ = _0056_ & _0066_;
  assign _0394_ = _0057_ & _0066_;
  assign _0397_ = _0354_ & _0384_;
  assign _0398_ = _0354_ ^ _0384_;
  assign _0399_ = ~(_0374_ & _0398_);
  assign _0400_ = _0374_ | _0398_;
  assign _0401_ = _0399_ & _0400_;
  assign _0073_ = ~(_0322_ ^ _0401_);
  assign _0402_ = ~(_0059_ & _0064_);
  assign _0403_ = ~(_0058_ & _0065_);
  assign _0404_ = _0056_ & _0067_;
  assign _0405_ = _0057_ & _0067_;
  assign _0406_ = _0394_ & _0404_;
  assign _0407_ = _0394_ ^ _0404_;
  assign _0408_ = ~(_0397_ & _0407_);
  assign _0409_ = _0397_ | _0407_;
  assign _0410_ = _0408_ & _0409_;
  assign _0411_ = ~(_0403_ ^ _0410_);
  assign _0412_ = ~(_0322_ & _0399_);
  assign _0413_ = _0400_ & _0412_;
  assign _0414_ = ~(_0411_ & _0413_);
  assign _0415_ = _0411_ | _0413_;
  assign _0416_ = _0414_ & _0415_;
  assign _0074_ = ~(_0402_ ^ _0416_);
  assign _0417_ = ~(_0060_ & _0064_);
  assign _0418_ = ~(_0059_ & _0065_);
  assign _0419_ = ~(_0058_ & _0066_);
  assign _0420_ = _0056_ & _0068_;
  assign _0421_ = _0057_ & _0068_;
  assign _0422_ = _0405_ & _0420_;
  assign _0423_ = _0405_ ^ _0420_;
  assign _0424_ = ~(_0406_ & _0423_);
  assign _0425_ = _0406_ | _0423_;
  assign _0426_ = _0424_ & _0425_;
  assign _0427_ = ~(_0419_ ^ _0426_);
  assign _0428_ = ~(_0403_ & _0408_);
  assign _0429_ = _0409_ & _0428_;
  assign _0430_ = ~(_0427_ & _0429_);
  assign _0431_ = _0427_ | _0429_;
  assign _0432_ = _0430_ & _0431_;
  assign _0433_ = ~(_0418_ ^ _0432_);
  assign _0434_ = ~(_0402_ & _0414_);
  assign _0435_ = _0415_ & _0434_;
  assign _0436_ = ~(_0433_ & _0435_);
  assign _0437_ = _0433_ | _0435_;
  assign _0438_ = _0436_ & _0437_;
  assign _0075_ = ~(_0417_ ^ _0438_);
  assign _0439_ = ~(_0061_ & _0064_);
  assign _0440_ = ~(_0060_ & _0065_);
  assign _0441_ = ~(_0059_ & _0066_);
  assign _0442_ = ~(_0058_ & _0067_);
  assign _0443_ = _0056_ & _0069_;
  assign _0444_ = ~(_0057_ & _0069_);
  assign _0445_ = _0421_ & _0443_;
  assign _0446_ = _0421_ ^ _0443_;
  assign _0447_ = ~(_0422_ & _0446_);
  assign _0448_ = _0422_ | _0446_;
  assign _0449_ = _0447_ & _0448_;
  assign _0450_ = ~(_0442_ ^ _0449_);
  assign _0451_ = ~(_0419_ & _0424_);
  assign _0452_ = _0425_ & _0451_;
  assign _0088_ = ~(_0450_ & _0452_);
  assign _0089_ = _0450_ | _0452_;
  assign _0090_ = _0088_ & _0089_;
  assign _0091_ = ~(_0441_ ^ _0090_);
  assign _0092_ = ~(_0418_ & _0430_);
  assign _0093_ = _0431_ & _0092_;
  assign _0094_ = ~(_0091_ & _0093_);
  assign _0095_ = _0091_ | _0093_;
  assign _0096_ = _0094_ & _0095_;
  assign _0097_ = ~(_0440_ ^ _0096_);
  assign _0098_ = ~(_0417_ & _0436_);
  assign _0099_ = _0437_ & _0098_;
  assign _0100_ = ~(_0097_ & _0099_);
  assign _0101_ = _0097_ | _0099_;
  assign _0102_ = _0100_ & _0101_;
  assign _0076_ = ~(_0439_ ^ _0102_);
  assign _0103_ = ~(_0062_ & _0064_);
  assign _0104_ = ~(_0061_ & _0065_);
  assign _0105_ = ~(_0060_ & _0066_);
  assign _0106_ = ~(_0059_ & _0067_);
  assign _0107_ = ~(_0058_ & _0068_);
  assign _0108_ = _0056_ & _0070_;
  assign _0109_ = _0057_ & _0070_;
  assign _0110_ = _0443_ & _0109_;
  assign _0111_ = ~(_0444_ ^ _0108_);
  assign _0112_ = ~(_0445_ & _0111_);
  assign _0113_ = _0445_ | _0111_;
  assign _0114_ = _0112_ & _0113_;
  assign _0115_ = ~(_0107_ ^ _0114_);
  assign _0116_ = ~(_0442_ & _0447_);
  assign _0117_ = _0448_ & _0116_;
  assign _0118_ = ~(_0115_ & _0117_);
  assign _0119_ = _0115_ | _0117_;
  assign _0120_ = _0118_ & _0119_;
  assign _0121_ = ~(_0106_ ^ _0120_);
  assign _0122_ = ~(_0441_ & _0088_);
  assign _0123_ = _0089_ & _0122_;
  assign _0124_ = ~(_0121_ & _0123_);
  assign _0125_ = _0121_ | _0123_;
  assign _0126_ = _0124_ & _0125_;
  assign _0127_ = ~(_0105_ ^ _0126_);
  assign _0128_ = ~(_0440_ & _0094_);
  assign _0129_ = _0095_ & _0128_;
  assign _0130_ = ~(_0127_ & _0129_);
  assign _0131_ = _0127_ | _0129_;
  assign _0132_ = _0130_ & _0131_;
  assign _0133_ = ~(_0104_ ^ _0132_);
  assign _0134_ = ~(_0439_ & _0100_);
  assign _0135_ = _0101_ & _0134_;
  assign _0136_ = ~(_0133_ & _0135_);
  assign _0137_ = _0133_ | _0135_;
  assign _0138_ = _0136_ & _0137_;
  assign _0077_ = ~(_0103_ ^ _0138_);
  assign _0139_ = _0063_ & _0064_;
  assign _0140_ = ~(_0062_ & _0065_);
  assign _0141_ = ~(_0061_ & _0066_);
  assign _0142_ = ~(_0060_ & _0067_);
  assign _0143_ = ~(_0059_ & _0068_);
  assign _0144_ = ~(_0107_ & _0112_);
  assign _0145_ = _0113_ & _0144_;
  assign _0146_ = _0058_ & _0069_;
  assign _0147_ = ~(_0071_ & _0110_);
  assign _0148_ = ~(_0071_ & _0056_);
  assign _0149_ = _0109_ & _0148_;
  assign _0150_ = _0109_ ^ _0148_;
  assign _0151_ = _0110_ | _0150_;
  assign _0152_ = ~(_0147_ & _0151_);
  assign _0153_ = ~(_0146_ ^ _0152_);
  assign _0154_ = ~(_0145_ & _0153_);
  assign _0155_ = _0145_ | _0153_;
  assign _0156_ = _0154_ & _0155_;
  assign _0157_ = ~(_0143_ ^ _0156_);
  assign _0158_ = ~(_0106_ & _0118_);
  assign _0159_ = _0119_ & _0158_;
  assign _0160_ = ~(_0157_ & _0159_);
  assign _0161_ = _0157_ | _0159_;
  assign _0162_ = _0160_ & _0161_;
  assign _0163_ = ~(_0142_ ^ _0162_);
  assign _0164_ = ~(_0105_ & _0124_);
  assign _0165_ = _0125_ & _0164_;
  assign _0166_ = ~(_0163_ & _0165_);
  assign _0167_ = _0163_ | _0165_;
  assign _0168_ = _0166_ & _0167_;
  assign _0169_ = ~(_0141_ ^ _0168_);
  assign _0170_ = ~(_0104_ & _0130_);
  assign _0171_ = _0131_ & _0170_;
  assign _0172_ = ~(_0169_ & _0171_);
  assign _0173_ = _0169_ | _0171_;
  assign _0174_ = _0172_ & _0173_;
  assign _0175_ = ~(_0140_ ^ _0174_);
  assign _0176_ = ~(_0103_ & _0136_);
  assign _0177_ = _0137_ & _0176_;
  assign _0178_ = ~(_0175_ & _0177_);
  assign _0179_ = _0175_ | _0177_;
  assign _0180_ = _0178_ & _0179_;
  assign _0078_ = ~(_0139_ ^ _0180_);
  assign _0181_ = ~(_0139_ & _0178_);
  assign _0182_ = _0179_ & _0181_;
  assign _0183_ = ~(_0063_ & _0065_);
  assign _0184_ = ~(_0062_ & _0066_);
  assign _0185_ = ~(_0061_ & _0067_);
  assign _0186_ = ~(_0060_ & _0068_);
  assign _0187_ = ~(_0059_ & _0069_);
  assign _0188_ = ~(_0146_ & _0151_);
  assign _0189_ = ~(_0147_ & _0188_);
  assign _0190_ = ~(_0058_ & _0070_);
  assign _0191_ = ~(_0071_ & _0149_);
  assign _0192_ = _0071_ & _0057_;
  assign _0193_ = _0109_ | _0192_;
  assign _0194_ = _0191_ & _0193_;
  assign _0195_ = ~(_0190_ ^ _0194_);
  assign _0196_ = ~(_0189_ & _0195_);
  assign _0197_ = _0189_ | _0195_;
  assign _0198_ = _0196_ & _0197_;
  assign _0199_ = ~(_0187_ ^ _0198_);
  assign _0200_ = ~(_0143_ & _0154_);
  assign _0201_ = _0155_ & _0200_;
  assign _0202_ = ~(_0199_ & _0201_);
  assign _0203_ = _0199_ | _0201_;
  assign _0204_ = _0202_ & _0203_;
  assign _0205_ = ~(_0186_ ^ _0204_);
  assign _0206_ = ~(_0142_ & _0160_);
  assign _0207_ = _0161_ & _0206_;
  assign _0208_ = ~(_0205_ & _0207_);
  assign _0209_ = _0205_ | _0207_;
  assign _0210_ = _0208_ & _0209_;
  assign _0211_ = ~(_0185_ ^ _0210_);
  assign _0212_ = ~(_0141_ & _0166_);
  assign _0213_ = _0167_ & _0212_;
  assign _0214_ = ~(_0211_ & _0213_);
  assign _0215_ = _0211_ | _0213_;
  assign _0216_ = _0214_ & _0215_;
  assign _0217_ = ~(_0184_ ^ _0216_);
  assign _0218_ = ~(_0140_ & _0172_);
  assign _0219_ = _0173_ & _0218_;
  assign _0220_ = ~(_0217_ & _0219_);
  assign _0221_ = _0217_ | _0219_;
  assign _0222_ = ~(_0220_ & _0221_);
  assign _0223_ = ~(_0183_ ^ _0222_);
  assign _0224_ = _0182_ & _0223_;
  assign _0079_ = _0182_ ^ _0223_;
  assign _0225_ = ~(_0183_ & _0221_);
  assign _0226_ = ~(_0220_ & _0225_);
  assign _0227_ = ~(_0224_ & _0226_);
  assign _0228_ = _0224_ | _0226_;
  assign _0229_ = _0227_ & _0228_;
  assign _0230_ = ~(_0063_ & _0066_);
  assign _0231_ = ~(_0062_ & _0067_);
  assign _0232_ = ~(_0061_ & _0068_);
  assign _0233_ = ~(_0060_ & _0069_);
  assign _0234_ = ~(_0059_ & _0070_);
  assign _0235_ = ~(_0190_ & _0191_);
  assign _0236_ = _0193_ & _0235_;
  assign _0237_ = _0057_ | _0058_;
  assign _0238_ = ~(_0057_ & _0058_);
  assign _0239_ = _0071_ & _0237_;
  assign _0240_ = _0238_ & _0239_;
  assign _0241_ = ~(_0236_ & _0240_);
  assign _0242_ = _0236_ | _0240_;
  assign _0243_ = _0241_ & _0242_;
  assign _0244_ = ~(_0234_ ^ _0243_);
  assign _0245_ = ~(_0187_ & _0196_);
  assign _0246_ = _0197_ & _0245_;
  assign _0247_ = ~(_0244_ & _0246_);
  assign _0248_ = _0244_ | _0246_;
  assign _0249_ = _0247_ & _0248_;
  assign _0250_ = ~(_0233_ ^ _0249_);
  assign _0251_ = ~(_0186_ & _0202_);
  assign _0252_ = _0203_ & _0251_;
  assign _0253_ = ~(_0250_ & _0252_);
  assign _0254_ = _0250_ | _0252_;
  assign _0255_ = _0253_ & _0254_;
  assign _0256_ = ~(_0232_ ^ _0255_);
  assign _0257_ = ~(_0185_ & _0208_);
  assign _0258_ = _0209_ & _0257_;
  assign _0259_ = ~(_0256_ & _0258_);
  assign _0260_ = _0256_ | _0258_;
  assign _0261_ = _0259_ & _0260_;
  assign _0262_ = ~(_0231_ ^ _0261_);
  assign _0263_ = ~(_0184_ & _0214_);
  assign _0264_ = _0215_ & _0263_;
  assign _0265_ = ~(_0262_ & _0264_);
  assign _0266_ = _0262_ | _0264_;
  assign _0267_ = _0265_ & _0266_;
  assign _0268_ = ~(_0230_ ^ _0267_);
  assign _0080_ = ~(_0229_ ^ _0268_);
  assign _0269_ = ~(_0227_ & _0268_);
  assign _0270_ = _0228_ & _0269_;
  assign _0271_ = ~(_0063_ & _0067_);
  assign _0272_ = ~(_0062_ & _0068_);
  assign _0273_ = ~(_0061_ & _0069_);
  assign _0274_ = ~(_0060_ & _0070_);
  assign _0275_ = _0059_ | _0237_;
  assign _0276_ = _0071_ & _0275_;
  assign _0277_ = ~(_0059_ & _0237_);
  assign _0278_ = _0276_ & _0277_;
  assign _0279_ = ~(_0234_ & _0241_);
  assign _0280_ = _0242_ & _0279_;
  assign _0281_ = ~(_0278_ & _0280_);
  assign _0282_ = _0278_ | _0280_;
  assign _0283_ = _0281_ & _0282_;
  assign _0284_ = ~(_0274_ ^ _0283_);
  assign _0285_ = ~(_0233_ & _0247_);
  assign _0286_ = _0248_ & _0285_;
  assign _0287_ = ~(_0284_ & _0286_);
  assign _0288_ = _0284_ | _0286_;
  assign _0289_ = _0287_ & _0288_;
  assign _0290_ = ~(_0273_ ^ _0289_);
  assign _0291_ = ~(_0232_ & _0253_);
  assign _0292_ = _0254_ & _0291_;
  assign _0293_ = ~(_0290_ & _0292_);
  assign _0294_ = _0290_ | _0292_;
  assign _0295_ = _0293_ & _0294_;
  assign _0296_ = ~(_0272_ ^ _0295_);
  assign _0297_ = ~(_0231_ & _0259_);
  assign _0298_ = _0260_ & _0297_;
  assign _0299_ = ~(_0296_ & _0298_);
  assign _0300_ = _0296_ | _0298_;
  assign _0301_ = _0299_ & _0300_;
  assign _0302_ = _0271_ ^ _0301_;
  assign _0303_ = ~(_0270_ & _0302_);
  assign _0304_ = _0270_ | _0302_;
  assign _0305_ = _0303_ & _0304_;
  assign _0306_ = ~(_0230_ & _0266_);
  assign _0307_ = _0265_ & _0306_;
  assign _0081_ = ~(_0305_ ^ _0307_);
  assign _0308_ = ~(_0303_ & _0307_);
  assign _0309_ = _0304_ & _0308_;
  assign _0310_ = ~(_0063_ & _0068_);
  assign _0311_ = ~(_0062_ & _0069_);
  assign _0312_ = ~(_0061_ & _0070_);
  assign _0313_ = _0071_ & _0060_;
  assign _0314_ = ~(_0276_ | _0313_);
  assign _0315_ = _0276_ ^ _0313_;
  assign _0316_ = ~(_0274_ & _0281_);
  assign _0317_ = _0282_ & _0316_;
  assign _0318_ = ~(_0315_ & _0317_);
  assign _0319_ = _0315_ | _0317_;
  assign _0320_ = _0318_ & _0319_;
  assign _0321_ = ~(_0312_ ^ _0320_);
  assign _0323_ = ~(_0273_ & _0287_);
  assign _0324_ = _0288_ & _0323_;
  assign _0325_ = ~(_0321_ & _0324_);
  assign _0326_ = _0321_ | _0324_;
  assign _0327_ = _0325_ & _0326_;
  assign _0328_ = ~(_0311_ ^ _0327_);
  assign _0329_ = ~(_0272_ & _0293_);
  assign _0330_ = _0294_ & _0329_;
  assign _0331_ = ~(_0328_ & _0330_);
  assign _0332_ = _0328_ | _0330_;
  assign _0334_ = _0331_ & _0332_;
  assign _0335_ = _0310_ ^ _0334_;
  assign _0336_ = ~(_0309_ & _0335_);
  assign _0337_ = _0309_ | _0335_;
  assign _0338_ = _0336_ & _0337_;
  assign _0339_ = ~(_0271_ & _0300_);
  assign _0340_ = _0299_ & _0339_;
  assign _0082_ = ~(_0338_ ^ _0340_);
  assign _0341_ = ~(_0336_ & _0340_);
  assign _0342_ = _0337_ & _0341_;
  assign _0344_ = ~(_0063_ & _0069_);
  assign _0345_ = ~(_0062_ & _0070_);
  assign _0346_ = ~(_0071_ & _0061_);
  assign _0347_ = _0314_ & _0346_;
  assign _0348_ = _0314_ ^ _0346_;
  assign _0349_ = ~(_0312_ & _0318_);
  assign _0350_ = _0319_ & _0349_;
  assign _0351_ = ~(_0348_ & _0350_);
  assign _0352_ = _0348_ | _0350_;
  assign _0353_ = _0351_ & _0352_;
  assign _0355_ = ~(_0345_ ^ _0353_);
  assign _0356_ = ~(_0311_ & _0325_);
  assign _0357_ = _0326_ & _0356_;
  assign _0358_ = ~(_0355_ & _0357_);
  assign _0359_ = _0355_ | _0357_;
  assign _0360_ = ~(_0358_ & _0359_);
  assign _0361_ = ~(_0344_ ^ _0360_);
  assign _0362_ = ~(_0342_ & _0361_);
  assign _0363_ = _0342_ | _0361_;
  assign _0364_ = _0362_ & _0363_;
  assign _0365_ = ~(_0310_ & _0332_);
  assign _0366_ = _0331_ & _0365_;
  assign _0083_ = ~(_0364_ ^ _0366_);
  assign _0367_ = _0063_ & _0070_;
  assign _0368_ = ~(_0071_ & _0062_);
  assign _0369_ = ~(_0347_ & _0368_);
  assign _0370_ = _0347_ ^ _0368_;
  assign _0371_ = ~(_0345_ & _0351_);
  assign _0372_ = _0352_ & _0371_;
  assign _0373_ = ~(_0370_ & _0372_);
  assign _0375_ = _0370_ | _0372_;
  assign _0376_ = _0373_ & _0375_;
  assign _0377_ = ~(_0367_ ^ _0376_);
  assign _0378_ = ~(_0362_ & _0366_);
  assign _0379_ = ~(_0363_ & _0378_);
  assign _0380_ = ~(_0344_ & _0359_);
  assign _0381_ = _0358_ & _0380_;
  assign _0382_ = ~(_0379_ & _0381_);
  assign _0383_ = ~(_0377_ ^ _0381_);
  assign _0084_ = ~(_0379_ ^ _0383_);
  assign _0385_ = ~(_0367_ & _0373_);
  assign _0386_ = ~(_0375_ & _0385_);
  assign _0387_ = ~(_0071_ & _0063_);
  assign _0388_ = ~(_0369_ & _0387_);
  assign _0389_ = _0369_ | _0387_;
  assign _0390_ = _0388_ & _0389_;
  assign _0391_ = _0377_ & _0382_;
  assign _0392_ = ~(_0390_ & _0391_);
  assign _0393_ = ~(_0390_ ^ _0391_);
  assign _0085_ = _0386_ ^ _0393_;
  assign _0395_ = ~(_0386_ & _0389_);
  assign _0396_ = ~(_0388_ & _0395_);
  assign _0086_ = _0392_ & _0396_;
  assign _0087_ = ~(_0333_ ^ _0343_);
  assign O = { S_8_7, S_8_6, S_8_5, S_8_4, S_8_3, S_8_2, S_8_1, S_8_0, S_7_0, S_6_0, S_5_0, S_4_0, S_3_0, S_2_0, S_1_0, S_0_0 };
  assign \U9.A  = S_0_1;
  assign \U9.B  = _0000_;
  assign C_1_0 = \U9.YC ;
  assign S_1_0 = \U9.YS ;
  assign \U72.A  = 1'h1;
  assign \U72.B  = C_8_6;
  assign \U72.C  = C_7_7;
  assign C_8_7 = \U72.YC ;
  assign S_8_7 = \U72.YS ;
  assign \U71.A  = S_7_7;
  assign \U71.B  = C_8_5;
  assign \U71.C  = C_7_6;
  assign C_8_6 = \U71.YC ;
  assign S_8_6 = \U71.YS ;
  assign \U70.A  = S_7_6;
  assign \U70.B  = C_8_4;
  assign \U70.C  = C_7_5;
  assign C_8_5 = \U70.YC ;
  assign S_8_5 = \U70.YS ;
  assign \U69.A  = S_7_5;
  assign \U69.B  = C_8_3;
  assign \U69.C  = C_7_4;
  assign C_8_4 = \U69.YC ;
  assign S_8_4 = \U69.YS ;
  assign \U68.A  = S_7_4;
  assign \U68.B  = C_8_2;
  assign \U68.C  = C_7_3;
  assign C_8_3 = \U68.YC ;
  assign S_8_3 = \U68.YS ;
  assign \U67.A  = S_7_3;
  assign \U67.B  = C_8_1;
  assign \U67.C  = C_7_2;
  assign C_8_2 = \U67.YC ;
  assign S_8_2 = \U67.YS ;
  assign \U66.A  = S_7_2;
  assign \U66.B  = C_8_0;
  assign \U66.C  = C_7_1;
  assign C_8_1 = \U66.YC ;
  assign S_8_1 = \U66.YS ;
  assign \U65.A  = S_7_1;
  assign \U65.B  = C_7_0;
  assign C_8_0 = \U65.YC ;
  assign S_8_0 = \U65.YS ;
  assign \U64.A  = C_6_7;
  assign \U64.B  = _0042_;
  assign C_7_7 = \U64.YC ;
  assign S_7_7 = \U64.YS ;
  assign \U63.A  = S_6_7;
  assign \U63.B  = C_6_6;
  assign \U63.C  = _0055_;
  assign C_7_6 = \U63.YC ;
  assign S_7_6 = \U63.YS ;
  assign \U62.A  = S_6_6;
  assign \U62.B  = C_6_5;
  assign \U62.C  = _0054_;
  assign C_7_5 = \U62.YC ;
  assign S_7_5 = \U62.YS ;
  assign \U61.A  = S_6_5;
  assign \U61.B  = C_6_4;
  assign \U61.C  = _0053_;
  assign C_7_4 = \U61.YC ;
  assign S_7_4 = \U61.YS ;
  assign \U60.A  = S_6_4;
  assign \U60.B  = C_6_3;
  assign \U60.C  = _0052_;
  assign C_7_3 = \U60.YC ;
  assign S_7_3 = \U60.YS ;
  assign \U59.A  = S_6_3;
  assign \U59.B  = C_6_2;
  assign \U59.C  = _0051_;
  assign C_7_2 = \U59.YC ;
  assign S_7_2 = \U59.YS ;
  assign \U58.A  = S_6_2;
  assign \U58.B  = C_6_1;
  assign \U58.C  = _0050_;
  assign C_7_1 = \U58.YC ;
  assign S_7_1 = \U58.YS ;
  assign \U57.A  = S_6_1;
  assign \U57.B  = C_6_0;
  assign \U57.C  = _0049_;
  assign C_7_0 = \U57.YC ;
  assign S_7_0 = \U57.YS ;
  assign \U56.A  = C_5_7;
  assign \U56.B  = _0048_;
  assign C_6_7 = \U56.YC ;
  assign S_6_7 = \U56.YS ;
  assign \U55.A  = S_5_7;
  assign \U55.B  = C_5_6;
  assign \U55.C  = _0041_;
  assign C_6_6 = \U55.YC ;
  assign S_6_6 = \U55.YS ;
  assign \U54.A  = S_5_6;
  assign \U54.B  = C_5_5;
  assign \U54.C  = _0040_;
  assign C_6_5 = \U54.YC ;
  assign S_6_5 = \U54.YS ;
  assign \U53.A  = S_5_5;
  assign \U53.B  = C_5_4;
  assign \U53.C  = _0039_;
  assign C_6_4 = \U53.YC ;
  assign S_6_4 = \U53.YS ;
  assign \U52.A  = S_5_4;
  assign \U52.B  = C_5_3;
  assign \U52.C  = _0038_;
  assign C_6_3 = \U52.YC ;
  assign S_6_3 = \U52.YS ;
  assign \U51.A  = S_5_3;
  assign \U51.B  = C_5_2;
  assign \U51.C  = _0037_;
  assign C_6_2 = \U51.YC ;
  assign S_6_2 = \U51.YS ;
  assign \U50.A  = S_5_2;
  assign \U50.B  = C_5_1;
  assign \U50.C  = _0036_;
  assign C_6_1 = \U50.YC ;
  assign S_6_1 = \U50.YS ;
  assign \U49.A  = S_5_1;
  assign \U49.B  = C_5_0;
  assign \U49.C  = _0035_;
  assign C_6_0 = \U49.YC ;
  assign S_6_0 = \U49.YS ;
  assign \U48.A  = C_4_7;
  assign \U48.B  = _0047_;
  assign C_5_7 = \U48.YC ;
  assign S_5_7 = \U48.YS ;
  assign \U47.A  = S_4_7;
  assign \U47.B  = C_4_6;
  assign \U47.C  = _0034_;
  assign C_5_6 = \U47.YC ;
  assign S_5_6 = \U47.YS ;
  assign \U46.A  = S_4_6;
  assign \U46.B  = C_4_5;
  assign \U46.C  = _0033_;
  assign C_5_5 = \U46.YC ;
  assign S_5_5 = \U46.YS ;
  assign \U45.A  = S_4_5;
  assign \U45.B  = C_4_4;
  assign \U45.C  = _0032_;
  assign C_5_4 = \U45.YC ;
  assign S_5_4 = \U45.YS ;
  assign \U44.A  = S_4_4;
  assign \U44.B  = C_4_3;
  assign \U44.C  = _0031_;
  assign C_5_3 = \U44.YC ;
  assign S_5_3 = \U44.YS ;
  assign \U43.A  = S_4_3;
  assign \U43.B  = C_4_2;
  assign \U43.C  = _0030_;
  assign C_5_2 = \U43.YC ;
  assign S_5_2 = \U43.YS ;
  assign \U42.A  = S_4_2;
  assign \U42.B  = C_4_1;
  assign \U42.C  = _0029_;
  assign C_5_1 = \U42.YC ;
  assign S_5_1 = \U42.YS ;
  assign \U41.A  = S_4_1;
  assign \U41.B  = C_4_0;
  assign \U41.C  = _0028_;
  assign C_5_0 = \U41.YC ;
  assign S_5_0 = \U41.YS ;
  assign \U40.A  = C_3_7;
  assign \U40.B  = _0046_;
  assign C_4_7 = \U40.YC ;
  assign S_4_7 = \U40.YS ;
  assign \U39.A  = S_3_7;
  assign \U39.B  = C_3_6;
  assign \U39.C  = _0027_;
  assign C_4_6 = \U39.YC ;
  assign S_4_6 = \U39.YS ;
  assign \U38.A  = S_3_6;
  assign \U38.B  = C_3_5;
  assign \U38.C  = _0026_;
  assign C_4_5 = \U38.YC ;
  assign S_4_5 = \U38.YS ;
  assign \U37.A  = S_3_5;
  assign \U37.B  = C_3_4;
  assign \U37.C  = _0025_;
  assign C_4_4 = \U37.YC ;
  assign S_4_4 = \U37.YS ;
  assign \U36.A  = S_3_4;
  assign \U36.B  = C_3_3;
  assign \U36.C  = _0024_;
  assign C_4_3 = \U36.YC ;
  assign S_4_3 = \U36.YS ;
  assign \U35.A  = S_3_3;
  assign \U35.B  = C_3_2;
  assign \U35.C  = _0023_;
  assign C_4_2 = \U35.YC ;
  assign S_4_2 = \U35.YS ;
  assign \U34.A  = S_3_2;
  assign \U34.B  = C_3_1;
  assign \U34.C  = _0022_;
  assign C_4_1 = \U34.YC ;
  assign S_4_1 = \U34.YS ;
  assign \U33.A  = S_3_1;
  assign \U33.B  = C_3_0;
  assign \U33.C  = _0021_;
  assign C_4_0 = \U33.YC ;
  assign S_4_0 = \U33.YS ;
  assign \U32.A  = C_2_7;
  assign \U32.B  = _0045_;
  assign C_3_7 = \U32.YC ;
  assign S_3_7 = \U32.YS ;
  assign \U31.A  = S_2_7;
  assign \U31.B  = C_2_6;
  assign \U31.C  = _0020_;
  assign C_3_6 = \U31.YC ;
  assign S_3_6 = \U31.YS ;
  assign \U30.A  = S_2_6;
  assign \U30.B  = C_2_5;
  assign \U30.C  = _0019_;
  assign C_3_5 = \U30.YC ;
  assign S_3_5 = \U30.YS ;
  assign \U29.A  = S_2_5;
  assign \U29.B  = C_2_4;
  assign \U29.C  = _0018_;
  assign C_3_4 = \U29.YC ;
  assign S_3_4 = \U29.YS ;
  assign \U28.A  = S_2_4;
  assign \U28.B  = C_2_3;
  assign \U28.C  = _0017_;
  assign C_3_3 = \U28.YC ;
  assign S_3_3 = \U28.YS ;
  assign \U27.A  = S_2_3;
  assign \U27.B  = C_2_2;
  assign \U27.C  = _0016_;
  assign C_3_2 = \U27.YC ;
  assign S_3_2 = \U27.YS ;
  assign \U26.A  = S_2_2;
  assign \U26.B  = C_2_1;
  assign \U26.C  = _0015_;
  assign C_3_1 = \U26.YC ;
  assign S_3_1 = \U26.YS ;
  assign \U25.A  = S_2_1;
  assign \U25.B  = C_2_0;
  assign \U25.C  = _0014_;
  assign C_3_0 = \U25.YC ;
  assign S_3_0 = \U25.YS ;
  assign \U24.A  = C_1_7;
  assign \U24.B  = _0044_;
  assign C_2_7 = \U24.YC ;
  assign S_2_7 = \U24.YS ;
  assign \U23.A  = S_1_7;
  assign \U23.B  = C_1_6;
  assign \U23.C  = _0013_;
  assign C_2_6 = \U23.YC ;
  assign S_2_6 = \U23.YS ;
  assign \U22.A  = S_1_6;
  assign \U22.B  = C_1_5;
  assign \U22.C  = _0012_;
  assign C_2_5 = \U22.YC ;
  assign S_2_5 = \U22.YS ;
  assign \U21.A  = S_1_5;
  assign \U21.B  = C_1_4;
  assign \U21.C  = _0011_;
  assign C_2_4 = \U21.YC ;
  assign S_2_4 = \U21.YS ;
  assign \U20.A  = S_1_4;
  assign \U20.B  = C_1_3;
  assign \U20.C  = _0010_;
  assign C_2_3 = \U20.YC ;
  assign S_2_3 = \U20.YS ;
  assign \U19.A  = S_1_3;
  assign \U19.B  = C_1_2;
  assign \U19.C  = _0009_;
  assign C_2_2 = \U19.YC ;
  assign S_2_2 = \U19.YS ;
  assign \U18.A  = S_1_2;
  assign \U18.B  = C_1_1;
  assign \U18.C  = _0008_;
  assign C_2_1 = \U18.YC ;
  assign S_2_1 = \U18.YS ;
  assign \U17.A  = S_1_1;
  assign \U17.B  = C_1_0;
  assign \U17.C  = _0007_;
  assign C_2_0 = \U17.YC ;
  assign S_2_0 = \U17.YS ;
  assign \U16.A  = 1'h1;
  assign \U16.B  = _0043_;
  assign C_1_7 = \U16.YC ;
  assign S_1_7 = \U16.YS ;
  assign \U15.A  = S_0_7;
  assign \U15.B  = _0006_;
  assign C_1_6 = \U15.YC ;
  assign S_1_6 = \U15.YS ;
  assign \U14.A  = S_0_6;
  assign \U14.B  = _0005_;
  assign C_1_5 = \U14.YC ;
  assign S_1_5 = \U14.YS ;
  assign \U13.A  = S_0_5;
  assign \U13.B  = _0004_;
  assign C_1_4 = \U13.YC ;
  assign S_1_4 = \U13.YS ;
  assign \U12.A  = S_0_4;
  assign \U12.B  = _0003_;
  assign C_1_3 = \U12.YC ;
  assign S_1_3 = \U12.YS ;
  assign \U11.A  = S_0_3;
  assign \U11.B  = _0002_;
  assign C_1_2 = \U11.YC ;
  assign S_1_2 = \U11.YS ;
  assign \U10.A  = S_0_2;
  assign \U10.B  = _0001_;
  assign C_1_1 = \U10.YC ;
  assign S_1_1 = \U10.YS ;
  assign \U17.YS  = _0073_;
  assign \U25.YS  = _0074_;
  assign \U33.YS  = _0075_;
  assign \U41.YS  = _0076_;
  assign \U49.YS  = _0077_;
  assign \U57.YS  = _0078_;
  assign \U65.YS  = _0079_;
  assign \U66.YS  = _0080_;
  assign \U67.YS  = _0081_;
  assign \U68.YS  = _0082_;
  assign \U69.YS  = _0083_;
  assign \U70.YS  = _0084_;
  assign \U71.YS  = _0085_;
  assign \U72.YS  = _0086_;
  assign \U9.YS  = _0087_;
  assign _0071_ = B[7];
  assign _0056_ = A[0];
  assign _0057_ = A[1];
  assign _0058_ = A[2];
  assign _0059_ = A[3];
  assign _0060_ = A[4];
  assign _0061_ = A[5];
  assign _0062_ = A[6];
  assign _0063_ = A[7];
  assign _0064_ = B[0];
  assign _0065_ = B[1];
  assign _0066_ = B[2];
  assign _0067_ = B[3];
  assign _0068_ = B[4];
  assign _0069_ = B[5];
  assign _0070_ = B[6];
  assign S_0_0 = _0072_;
endmodule
