/* Generated by Yosys 0.38 (git sha1 543faed9c, gcc 13.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -Os) */

(* top =  1  *)
(* src = "./add16se_20J.v:18.1-156.10" *)
module add16se_20J(A, B, O);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  (* src = "./add16se_20J.v:24.14-24.15" *)
  input [15:0] A;
  wire [15:0] A;
  (* src = "./add16se_20J.v:25.14-25.15" *)
  input [15:0] B;
  wire [15:0] B;
  (* src = "./add16se_20J.v:26.15-26.16" *)
  output [16:0] O;
  wire [16:0] O;
  (* src = "./add16se_20J.v:32.62-32.69" *)
  wire sig_129;
  (* src = "./add16se_20J.v:32.70-32.77" *)
  wire sig_130;
  (* src = "./add16se_20J.v:32.78-32.85" *)
  wire sig_131;
  (* src = "./add16se_20J.v:32.86-32.93" *)
  wire sig_132;
  (* src = "./add16se_20J.v:32.94-32.101" *)
  wire sig_133;
  (* src = "./add16se_20J.v:32.102-32.109" *)
  wire sig_134;
  (* src = "./add16se_20J.v:32.110-32.117" *)
  wire sig_135;
  (* src = "./add16se_20J.v:32.118-32.125" *)
  wire sig_136;
  (* src = "./add16se_20J.v:32.126-32.133" *)
  wire sig_137;
  (* src = "./add16se_20J.v:32.134-32.141" *)
  wire sig_138;
  (* src = "./add16se_20J.v:32.142-32.149" *)
  wire sig_139;
  (* src = "./add16se_20J.v:32.150-32.157" *)
  wire sig_140;
  (* src = "./add16se_20J.v:32.158-32.165" *)
  wire sig_141;
  (* src = "./add16se_20J.v:33.6-33.13" *)
  wire sig_142;
  (* src = "./add16se_20J.v:33.14-33.21" *)
  wire sig_143;
  assign _040_ = ~(B[2] ^ A[2]);
  assign sig_129 = ~(_040_ ^ A[1]);
  assign _041_ = ~(B[3] ^ A[3]);
  assign _042_ = B[2] & A[2];
  assign _043_ = A[1] & ~(_040_);
  assign _044_ = _043_ | _042_;
  assign sig_130 = ~(_044_ ^ _041_);
  assign _045_ = ~(B[4] ^ A[4]);
  assign _046_ = ~(B[3] & A[3]);
  assign _047_ = _044_ & ~(_041_);
  assign _048_ = _046_ & ~(_047_);
  assign sig_131 = _048_ ^ _045_;
  assign _049_ = ~(B[5] ^ A[5]);
  assign _050_ = B[4] & A[4];
  assign _051_ = ~(_046_ | _045_);
  assign _052_ = _051_ | _050_;
  assign _053_ = _045_ | _041_;
  assign _054_ = _053_ | ~(_044_);
  assign _055_ = _054_ & ~(_052_);
  assign sig_132 = _055_ ^ _049_;
  assign _056_ = ~(B[6] ^ A[6]);
  assign _057_ = ~(B[5] & A[5]);
  assign _058_ = ~(_055_ | _049_);
  assign _059_ = _057_ & ~(_058_);
  assign sig_133 = _059_ ^ _056_;
  assign _060_ = ~(B[7] ^ A[7]);
  assign _061_ = B[6] & A[6];
  assign _062_ = ~(_057_ | _056_);
  assign _063_ = _062_ | _061_;
  assign _064_ = _056_ | _049_;
  assign _065_ = _052_ & ~(_064_);
  assign _066_ = _065_ | _063_;
  assign _067_ = _064_ | _053_;
  assign _068_ = _044_ & ~(_067_);
  assign _069_ = _068_ | _066_;
  assign sig_134 = ~(_069_ ^ _060_);
  assign _070_ = ~(B[8] ^ A[8]);
  assign _071_ = ~(B[7] & A[7]);
  assign _072_ = _069_ & ~(_060_);
  assign _073_ = _071_ & ~(_072_);
  assign sig_135 = _073_ ^ _070_;
  assign _074_ = ~(B[9] ^ A[9]);
  assign _075_ = B[8] & A[8];
  assign _076_ = ~(_071_ | _070_);
  assign _077_ = _076_ | _075_;
  assign _078_ = _070_ | _060_;
  assign _079_ = _078_ | ~(_069_);
  assign _080_ = _079_ & ~(_077_);
  assign sig_136 = _080_ ^ _074_;
  assign _081_ = ~(B[10] ^ A[10]);
  assign _082_ = ~(B[9] & A[9]);
  assign _083_ = ~(_080_ | _074_);
  assign _084_ = _082_ & ~(_083_);
  assign sig_137 = _084_ ^ _081_;
  assign _085_ = ~(B[11] ^ A[11]);
  assign _000_ = B[10] & A[10];
  assign _001_ = ~(_082_ | _081_);
  assign _002_ = _001_ | _000_;
  assign _003_ = _081_ | _074_;
  assign _004_ = _077_ & ~(_003_);
  assign _005_ = _004_ | _002_;
  assign _006_ = _003_ | _078_;
  assign _007_ = _069_ & ~(_006_);
  assign _008_ = ~(_007_ | _005_);
  assign sig_138 = _008_ ^ _085_;
  assign _009_ = ~(B[12] ^ A[12]);
  assign _010_ = ~(B[11] & A[11]);
  assign _011_ = ~(_008_ | _085_);
  assign _012_ = _010_ & ~(_011_);
  assign sig_139 = _012_ ^ _009_;
  assign _013_ = ~(B[13] ^ A[13]);
  assign _014_ = B[12] & A[12];
  assign _015_ = ~(_010_ | _009_);
  assign _016_ = _015_ | _014_;
  assign _017_ = _009_ | _085_;
  assign _018_ = _017_ | _008_;
  assign _019_ = _018_ & ~(_016_);
  assign sig_140 = _019_ ^ _013_;
  assign _020_ = ~(B[14] ^ A[14]);
  assign _021_ = ~(B[13] & A[13]);
  assign _022_ = ~(_019_ | _013_);
  assign _023_ = _021_ & ~(_022_);
  assign sig_141 = _023_ ^ _020_;
  assign _024_ = ~(B[15] ^ A[15]);
  assign _025_ = ~(B[14] & A[14]);
  assign _026_ = ~(_021_ | _020_);
  assign _027_ = _025_ & ~(_026_);
  assign _028_ = _020_ | _013_;
  assign _029_ = _016_ & ~(_028_);
  assign _030_ = _027_ & ~(_029_);
  assign _031_ = _028_ | _017_;
  assign _032_ = _005_ & ~(_031_);
  assign _033_ = _030_ & ~(_032_);
  assign _034_ = _031_ | _006_;
  assign _035_ = _069_ & ~(_034_);
  assign _036_ = _033_ & ~(_035_);
  assign sig_142 = _036_ ^ _024_;
  assign _037_ = ~(B[15] & A[15]);
  assign _038_ = ~(_036_ | _024_);
  assign _039_ = _037_ & ~(_038_);
  assign sig_143 = _039_ ^ _024_;
  assign O = { sig_143, sig_142, sig_141, sig_140, sig_139, sig_138, sig_137, sig_136, sig_135, sig_134, sig_133, sig_132, sig_131, sig_130, sig_129, B[1], 1'h0 };
endmodule
