/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "./mul8s_1L12/mul8s_1L12.v:19" *)
module mul8s_1L12(A, B, O);
  (* src = "./mul8s_1L12/mul8s_1L12.v:33" *)
  wire _000_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:47" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:39" *)
  wire _026_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:40" *)
  wire _027_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:41" *)
  wire _028_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:42" *)
  wire _029_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:43" *)
  wire _030_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:44" *)
  wire _031_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:45" *)
  wire _032_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:46" *)
  wire _033_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:20" *)
  wire _034_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:20" *)
  wire _035_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:21" *)
  wire _036_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:21" *)
  wire _037_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:21" *)
  wire _038_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:21" *)
  wire _039_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:21" *)
  wire _040_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:21" *)
  wire _041_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:21" *)
  wire _042_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:21" *)
  wire _043_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire _044_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire _045_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire _046_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire _047_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire _048_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire _049_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire _050_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire _051_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire _052_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:40|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  (* src = "./mul8s_1L12/mul8s_1L12.v:20" *)
  input [7:0] A;
  (* src = "./mul8s_1L12/mul8s_1L12.v:21" *)
  input [7:0] B;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire C_6_1;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire C_6_7;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire C_7_0;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire C_7_1;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire C_7_2;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire C_7_3;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire C_7_4;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire C_7_5;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire C_7_6;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire C_7_7;
  (* src = "./mul8s_1L12/mul8s_1L12.v:22" *)
  output [15:0] O;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_0_7;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_1_6;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_2_5;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_3_4;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_4_3;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_5_2;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_6_0;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_6_1;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_6_2;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_6_3;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_6_4;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_6_5;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_6_6;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_6_7;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_7_0;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_7_1;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_7_2;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_7_3;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_7_4;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_7_5;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_7_6;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_7_7;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_8_0;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_8_1;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_8_2;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_8_3;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_8_4;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_8_5;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_8_6;
  (* src = "./mul8s_1L12/mul8s_1L12.v:24" *)
  wire S_8_7;
  (* src = "./mul8s_1L12/mul8s_1L12.v:33|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292374.A ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:33|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292374.B ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:33|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292374.YC ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:33|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292374.YS ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:39|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292380.A ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:39|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292380.B ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:39|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292380.YC ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:39|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292380.YS ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:40|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292381.A ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:40|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292381.B ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:40|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292381.YC ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:40|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292381.YS ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:41|./mul8s_1L12/mul8s_1L12.v:59" *)
  wire \U292382.A ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:41|./mul8s_1L12/mul8s_1L12.v:59" *)
  wire \U292382.B ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:41|./mul8s_1L12/mul8s_1L12.v:59" *)
  wire \U292382.C ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:41|./mul8s_1L12/mul8s_1L12.v:59" *)
  wire \U292382.YC ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:41|./mul8s_1L12/mul8s_1L12.v:59" *)
  wire \U292382.YS ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:42|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292383.A ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:42|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292383.B ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:42|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292383.YC ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:42|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292383.YS ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:43|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292384.A ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:43|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292384.B ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:43|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292384.YC ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:43|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292384.YS ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:44|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292385.A ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:44|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292385.B ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:44|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292385.YC ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:44|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292385.YS ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:45|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292386.A ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:45|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292386.B ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:45|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292386.YC ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:45|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292386.YS ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:46|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292387.A ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:46|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292387.B ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:46|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292387.YC ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:46|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292387.YS ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:47|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292388.A ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:47|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292388.B ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:47|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292388.YC ;
  (* src = "./mul8s_1L12/mul8s_1L12.v:47|./mul8s_1L12/mul8s_1L12.v:54" *)
  wire \U292388.YS ;
  assign _054_ = ~_035_;
  assign _055_ = ~_034_;
  assign _056_ = ~(_035_ & _036_);
  assign _057_ = ~(_034_ & _037_);
  assign _058_ = _056_ & _057_;
  assign _053_ = _056_ ^ _057_;
  assign _059_ = _054_ & _037_;
  assign _060_ = ~(_038_ & _059_);
  assign _061_ = _038_ | _059_;
  assign _062_ = ~(_034_ & _061_);
  assign _063_ = ~_062_;
  assign _064_ = ~(_055_ & _037_);
  assign _065_ = _059_ | _064_;
  assign _066_ = ~(_062_ & _065_);
  assign _067_ = ~(_060_ & _066_);
  assign _068_ = _058_ & _067_;
  assign _069_ = ~(_035_ & _038_);
  assign _070_ = _039_ & _034_;
  assign _071_ = _069_ & _070_;
  assign _072_ = _069_ ^ _070_;
  assign _073_ = ~(_063_ & _072_);
  assign _074_ = ~(_062_ ^ _072_);
  assign _075_ = ~(_068_ & _074_);
  assign _046_ = _068_ ^ _074_;
  assign _076_ = ~(_073_ & _075_);
  assign _077_ = ~(_039_ & _035_);
  assign _078_ = _040_ & _034_;
  assign _079_ = _077_ & _078_;
  assign _080_ = _077_ ^ _078_;
  assign _081_ = ~(_071_ & _080_);
  assign _082_ = _071_ ^ _080_;
  assign _083_ = ~(_076_ & _082_);
  assign _047_ = _076_ ^ _082_;
  assign _084_ = _081_ & _083_;
  assign _085_ = ~(_035_ & _040_);
  assign _086_ = _041_ & _034_;
  assign _087_ = _085_ & _086_;
  assign _088_ = _085_ ^ _086_;
  assign _089_ = ~(_079_ & _088_);
  assign _090_ = _079_ | _088_;
  assign _091_ = _089_ & _090_;
  assign _048_ = ~(_084_ ^ _091_);
  assign _092_ = ~(_035_ & _041_);
  assign _093_ = _042_ & _034_;
  assign _094_ = _092_ & _093_;
  assign _095_ = _092_ ^ _093_;
  assign _096_ = ~(_087_ & _095_);
  assign _097_ = _087_ ^ _095_;
  assign _098_ = ~(_084_ & _089_);
  assign _099_ = _090_ & _098_;
  assign _100_ = ~(_097_ & _099_);
  assign _049_ = _097_ ^ _099_;
  assign _101_ = _096_ & _100_;
  assign _102_ = _035_ & _042_;
  assign _103_ = _034_ & _043_;
  assign _104_ = ~(_102_ ^ _103_);
  assign _105_ = ~(_094_ & _104_);
  assign _106_ = _094_ | _104_;
  assign _107_ = _105_ & _106_;
  assign _050_ = ~(_101_ ^ _107_);
  assign _108_ = ~(_035_ & _043_);
  assign _109_ = _093_ | _108_;
  assign _110_ = ~(_101_ & _105_);
  assign _111_ = ~(_106_ & _110_);
  assign _052_ = _109_ & _111_;
  assign _051_ = ~(_109_ ^ _111_);
  assign _045_ = _058_ ^ _067_;
  assign _044_ = _034_ & _036_;
  assign O = { S_8_7, S_8_6, S_8_5, S_8_4, S_8_3, S_8_2, S_8_1, S_8_0, S_7_0, S_6_0, 6'h00 };
  assign S_0_7 = 1'h1;
  assign S_1_6 = 1'h1;
  assign S_2_5 = 1'h1;
  assign S_3_4 = 1'h1;
  assign S_4_3 = 1'h1;
  assign S_5_2 = 1'h1;
  assign \U292374.A  = 1'h1;
  assign \U292374.B  = _000_;
  assign C_6_1 = \U292374.YC ;
  assign S_6_1 = \U292374.YS ;
  assign \U292380.A  = 1'h1;
  assign \U292380.B  = _026_;
  assign C_6_7 = \U292380.YC ;
  assign S_6_7 = \U292380.YS ;
  assign \U292381.A  = S_6_1;
  assign \U292381.B  = _027_;
  assign C_7_0 = \U292381.YC ;
  assign S_7_0 = \U292381.YS ;
  assign \U292382.A  = S_6_2;
  assign \U292382.B  = C_6_1;
  assign \U292382.C  = _028_;
  assign C_7_1 = \U292382.YC ;
  assign S_7_1 = \U292382.YS ;
  assign \U292383.A  = S_6_3;
  assign \U292383.B  = _029_;
  assign C_7_2 = \U292383.YC ;
  assign S_7_2 = \U292383.YS ;
  assign \U292384.A  = S_6_4;
  assign \U292384.B  = _030_;
  assign C_7_3 = \U292384.YC ;
  assign S_7_3 = \U292384.YS ;
  assign \U292385.A  = S_6_5;
  assign \U292385.B  = _031_;
  assign C_7_4 = \U292385.YC ;
  assign S_7_4 = \U292385.YS ;
  assign \U292386.A  = S_6_6;
  assign \U292386.B  = _032_;
  assign C_7_5 = \U292386.YC ;
  assign S_7_5 = \U292386.YS ;
  assign \U292387.A  = S_6_7;
  assign \U292387.B  = _033_;
  assign C_7_6 = \U292387.YC ;
  assign S_7_6 = \U292387.YS ;
  assign \U292388.A  = C_6_7;
  assign \U292388.B  = _001_;
  assign C_7_7 = \U292388.YC ;
  assign S_7_7 = \U292388.YS ;
  assign \U292381.YS  = _053_;
  assign _039_ = B[3];
  assign _035_ = A[7];
  assign _038_ = B[2];
  assign _041_ = B[5];
  assign _040_ = B[4];
  assign _042_ = B[6];
  assign _034_ = A[6];
  assign _043_ = B[7];
  assign _036_ = B[0];
  assign _037_ = B[1];
  assign S_8_1 = _046_;
  assign S_8_2 = _047_;
  assign S_8_3 = _048_;
  assign S_8_4 = _049_;
  assign S_8_5 = _050_;
  assign S_8_6 = _051_;
  assign S_8_7 = _052_;
  assign S_8_0 = _045_;
  assign S_6_0 = _044_;
endmodule
